apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: this-is-my-app
  template:
    metadata:
      labels:
        app: this-is-my-app
    spec:
      containers:
        - name: my-container
          image: my-app:1.0.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/myapp
        - name: promtail
          image: grafana/promtail:latest
          args:
            - -config.file=/etc/promtail/promtail.yml
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail
            - name: app-logs
              mountPath: /var/log/myapp
            - name: positions
              mountPath: /run/promtail
      volumes:
        - name: app-logs
          emptyDir: {}
        - name: promtail-config
          configMap:
            name: promtail-config
        - name: positions
          emptyDir: {}
