apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 80        # 클러스터 내부에서 사용하는 포트
      targetPort: 8080 # Pod에서 사용하는 포트 (컨테이너의 containerPort와 일치)
      nodePort: 30007  # 외부에서 접근 가능한 포트 (30000-32767 범위에서 지정)
